import request from 'supertest';
import { createApp } from '../../src/http/app';
import { resetDb, standardFixture, bearer } from '../helpers';
import { recordAudit, getHistory } from '../../src/modules/audit/audit.service';
import { config } from '../../src/config';
import { shipAuditToS3, getShippedAudit, clearShippedAudit } from '../../src/modules/audit/s3shipper';
import { randomUUID } from 'crypto';

const app = createApp();

describe('attachments', () => {
  let fx: Awaited<ReturnType<typeof standardFixture>>;
  beforeEach(async () => {
    await resetDb();
    fx = await standardFixture();
  });

  it('returns a presigned (mock) url', async () => {
    const res = await request(app)
      .post('/attachments/presign')
      .set('Authorization', bearer(fx.emp))
      .send({ filename: 'bill.png', contentType: 'image/png' });
    expect(res.status).toBe(200);
    expect(res.body.uploadUrl).toContain('mock-s3');
    expect(res.body.key).toContain(fx.orgId);
  });

  it('validates presign payload', async () => {
    const res = await request(app)
      .post('/attachments/presign')
      .set('Authorization', bearer(fx.emp))
      .send({});
    expect(res.status).toBe(400);
  });
});

describe('notifications', () => {
  let fx: Awaited<ReturnType<typeof standardFixture>>;
  beforeEach(async () => {
    await resetDb();
    fx = await standardFixture();
  });

  it('lists notifications generated by the workflow', async () => {
    const d = await request(app)
      .post('/expenses')
      .set('Authorization', bearer(fx.emp))
      .send({ type: 'reimbursement', amount: 3000, currency: 'INR' });
    await request(app).post(`/expenses/${d.body.id}/submit`).set('Authorization', bearer(fx.emp));

    // Manager should have an approval_requested notification
    const res = await request(app).get('/notifications').set('Authorization', bearer(fx.manager));
    expect(res.status).toBe(200);
    expect(res.body.length).toBeGreaterThanOrEqual(1);

    const markRes = await request(app)
      .post(`/notifications/${res.body[0].id}/read`)
      .set('Authorization', bearer(fx.manager));
    expect(markRes.body.read).toBe(true);
  });

  it('404 when marking a missing notification', async () => {
    const res = await request(app)
      .post('/notifications/00000000-0000-0000-0000-000000000000/read')
      .set('Authorization', bearer(fx.manager));
    expect(res.status).toBe(404);
  });
});

describe('audit', () => {
  let fx: Awaited<ReturnType<typeof standardFixture>>;
  beforeEach(async () => {
    await resetDb();
    fx = await standardFixture();
    clearShippedAudit();
  });

  it('records and returns history for an expense', async () => {
    const d = await request(app)
      .post('/expenses')
      .set('Authorization', bearer(fx.emp))
      .send({ type: 'reimbursement', amount: 3000, currency: 'INR' });
    await request(app).post(`/expenses/${d.body.id}/submit`).set('Authorization', bearer(fx.emp));
    await request(app)
      .post(`/expenses/${d.body.id}/approve`)
      .set('Authorization', bearer(fx.manager))
      .send({ reason: 'ok' });

    const res = await request(app)
      .get(`/expenses/${d.body.id}/history`)
      .set('Authorization', bearer(fx.emp));
    expect(res.status).toBe(200);
    const actions = res.body.map((r: { action: string }) => r.action);
    expect(actions).toContain('expense.created');
    expect(actions).toContain('expense.submitted');
    expect(actions).toContain('expense.approved');
  });

  it('records audit without a transaction client', async () => {
    const entityId = randomUUID();
    await recordAudit({
      orgId: fx.orgId,
      actorId: fx.admin.id,
      action: 'test.action',
      entityType: 'test',
      entityId
    });
    const history = await getHistory(fx.orgId, 'test', entityId);
    expect(history).toHaveLength(1);
  });

  it('ships audit to S3 only when flag enabled', async () => {
    const original = config.auditS3ShippingEnabled;
    (config as { auditS3ShippingEnabled: boolean }).auditS3ShippingEnabled = false;
    await shipAuditToS3({ id: 'a1', orgId: fx.orgId });
    expect(Object.keys(getShippedAudit())).toHaveLength(0);

    (config as { auditS3ShippingEnabled: boolean }).auditS3ShippingEnabled = true;
    await shipAuditToS3({ id: 'a2', orgId: fx.orgId });
    expect(Object.keys(getShippedAudit()).length).toBeGreaterThan(0);

    (config as { auditS3ShippingEnabled: boolean }).auditS3ShippingEnabled = original;
  });
});

describe('routing', () => {
  it('returns 404 envelope for unknown route', async () => {
    const res = await request(app).get('/nope').set('Accept', 'application/json');
    expect(res.status).toBe(404);
    expect(res.body.error.code).toBe('NOT_FOUND');
  });
});
